//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKZSoft.Twitter.TwitterData.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SKZSoft.Twitter.TwitterData.Exceptions.ExceptionStrings", typeof(ExceptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter reports that it is down for maintenance or being upgraded. Please try again later..
        /// </summary>
        internal static string TwitterErrorBadGateway {
            get {
                return ResourceManager.GetString("TwitterErrorBadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tweet you are trying to send is a duplicate of another recent tweet.
        ///Either delete the other tweet or rephrase the one you are trying to send..
        /// </summary>
        internal static string TwitterErrorDuplicateStatus {
            get {
                return ResourceManager.GetString("TwitterErrorDuplicateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter reports that it has imposed Rate Limits. Your account is too active.
        ///Please slow down your usage, and try again in 15 minutes..
        /// </summary>
        internal static string TwitterErrorRateLimits {
            get {
                return ResourceManager.GetString("TwitterErrorRateLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter reports that you have too many connections.
        ///Log out from some applications..
        /// </summary>
        internal static string TwitterErrorTooManyRequests {
            get {
                return ResourceManager.GetString("TwitterErrorTooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter reports a problem with authorization. Cannot complete request..
        /// </summary>
        internal static string TwitterErrorUnauthorized {
            get {
                return ResourceManager.GetString("TwitterErrorUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter could not process the image correctly..
        /// </summary>
        internal static string TwitterErrorUnprocessableEntity {
            get {
                return ResourceManager.GetString("TwitterErrorUnprocessableEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter reports that it is overloaded at the moment. Please try again later..
        /// </summary>
        internal static string TwitterServiceUnavailable {
            get {
                return ResourceManager.GetString("TwitterServiceUnavailable", resourceCulture);
            }
        }
    }
}
