//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKZSoft.SKZTweets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SKZSoft.SKZTweets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKZTweets.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following IDs were inavlid. There were {0} good IDs. 
        ///Do you wish to proceed?
        ///{1}.
        /// </summary>
        internal static string BadIDsFound {
            get {
                return ResourceManager.GetString("BadIDsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [default browser].
        /// </summary>
        internal static string BrowserUseDefault {
            get {
                return ResourceManager.GetString("BrowserUseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find tweet with ID {0}.
        /// </summary>
        internal static string CannotFindTweet {
            get {
                return ResourceManager.GetString("CannotFindTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters text become {1} characters in {2} tweets.
        /// </summary>
        internal static string CharacterCount {
            get {
                return ResourceManager.GetString("CharacterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing this form would mean that the data will be lost.
        ///Do you wish to close the form and lose the data?.
        /// </summary>
        internal static string ClosingFormLoseData {
            get {
                return ResourceManager.GetString("ClosingFormLoseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing this form would stop the current action.
        ///Do you wish to proceed?.
        /// </summary>
        internal static string ClosingWouldInterruptConfirm {
            get {
                return ResourceManager.GetString("ClosingWouldInterruptConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses Twitter developer credentials. To get your credentials, go to:
        ///https://apps.twitter.com
        ///
        ///and click &quot;Create New App&quot;.
        ///Enter any details you wish, but they must be unique and pass Twitter&apos;s own validation.
        ///
        ///The website must be a valid website (but can be any)
        ///Leave the &quot;Callback URL&quot; blank.
        ///
        ///Once you have registered your &quot;app&quot;, a new screen will appear with some details.
        ///Ensure that &quot;Access level&quot; says &quot;Read and Write&quot; and modify it if it does not.
        ///Click &quot;manage keys and acces [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CredentialsHelp {
            get {
                return ResourceManager.GetString("CredentialsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all the tweets which have been posted as a thread.
        ///Do you wish to proceed?.
        /// </summary>
        internal static string DeleteTweetsConfirm {
            get {
                return ResourceManager.GetString("DeleteTweetsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to discard the changes?.
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMBroadcast complete..
        /// </summary>
        internal static string DMBroadCastComplete {
            get {
                return ResourceManager.GetString("DMBroadCastComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of the {0} IDs provided, {1} were duplicates and {2} were invalid..
        /// </summary>
        internal static string DMValidationFailures {
            get {
                return ResourceManager.GetString("DMValidationFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will send DMs to {0} account(s)..
        /// </summary>
        internal static string DMWillSendNumber {
            get {
                return ResourceManager.GetString("DMWillSendNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to proceed?.
        /// </summary>
        internal static string DoYouWishToProceed {
            get {
                return ResourceManager.GetString("DoYouWishToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out will close all open windows, stop all current jobs, and delete your Twitter credentials.
        ///
        ///You will have to authenticate this application on Twitter again before you can use it.
        ///
        ///Do you wish to proceed?.
        /// </summary>
        internal static string DoYouWishToSignOut {
            get {
                return ResourceManager.GetString("DoYouWishToSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only drag picture files to a tweet..
        /// </summary>
        internal static string DragErrorOnlyPictureFiles {
            get {
                return ResourceManager.GetString("DragErrorOnlyPictureFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweets can only have four images at most..
        /// </summary>
        internal static string DragErrorTooManyPictures {
            get {
                return ResourceManager.GetString("DragErrorTooManyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping files here will replace any existing tweets and create a new thread of the file names and the pictures. Do you wish to proceed, and delete any existing tweets?.
        /// </summary>
        internal static string DroppingFilesNewThreadConf {
            get {
                return ResourceManager.GetString("DroppingFilesNewThreadConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Details follow:
        ///{0}.
        /// </summary>
        internal static string ErrorDialogBody {
            get {
                return ResourceManager.GetString("ErrorDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Error: {1}.
        /// </summary>
        internal static string ErrorOccurredInJob {
            get {
                return ResourceManager.GetString("ErrorOccurredInJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating counts.
        /// </summary>
        internal static string ErrorUpdatingCounts {
            get {
                return ResourceManager.GetString("ErrorUpdatingCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file [{0}] does not exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be numeric..
        /// </summary>
        internal static string IntervalMustBeNumeric {
            get {
                return ResourceManager.GetString("IntervalMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The intro text is too long for these settings. It has been trimmed..
        /// </summary>
        internal static string IntroTooLongForSettings {
            get {
                return ResourceManager.GetString("IntroTooLongForSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time &quot;{0}&quot;.
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tweet ID.
        /// </summary>
        internal static string InvalidTweetId {
            get {
                return ResourceManager.GetString("InvalidTweetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job &quot;{0}&quot; reports the following error:.
        /// </summary>
        internal static string JobException {
            get {
                return ResourceManager.GetString("JobException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last component of a schedule cannot be removed. Add more components before removing this one..
        /// </summary>
        internal static string LastComponentCannotBeRemoved {
            get {
                return ResourceManager.GetString("LastComponentCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Log Directory {0}.
        /// </summary>
        internal static string LogDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("LogDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media uploaded.
        /// </summary>
        internal static string MediaUploaded {
            get {
                return ResourceManager.GetString("MediaUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes must be a number.
        /// </summary>
        internal static string MinutesMustBeNumeric {
            get {
                return ResourceManager.GetString("MinutesMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes must be a number bigger than zero..
        /// </summary>
        internal static string MinutesOutOfRange {
            get {
                return ResourceManager.GetString("MinutesOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid IDs found..
        /// </summary>
        internal static string NoGoodIDsFound {
            get {
                return ResourceManager.GetString("NoGoodIDsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more work to do.
        /// </summary>
        internal static string NoMoreWork {
            get {
                return ResourceManager.GetString("NoMoreWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid tweet URL..
        /// </summary>
        internal static string NotaTweetURL {
            get {
                return ResourceManager.GetString("NotaTweetURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some text to tweet.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tweet could be found at that URL.
        /// </summary>
        internal static string NoTweetAtURL {
            get {
                return ResourceManager.GetString("NoTweetAtURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not authenticate. Please check your PIN..
        /// </summary>
        internal static string PINError {
            get {
                return ResourceManager.GetString("PINError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a twwet from the list.
        /// </summary>
        internal static string PleaseSelectATweetFromTheList {
            get {
                return ResourceManager.GetString("PleaseSelectATweetFromTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following problem(s) were found:.
        /// </summary>
        internal static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent {0} of {1}.
        /// </summary>
        internal static string ProgressDMSend {
            get {
                return ResourceManager.GetString("ProgressDMSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A job of this type is already underway. Please let it finish first..
        /// </summary>
        internal static string QueueManagerDuplicate {
            get {
                return ResourceManager.GetString("QueueManagerDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform this action. This item is closing..
        /// </summary>
        internal static string QueueManagerTerminating {
            get {
                return ResourceManager.GetString("QueueManagerTerminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to remove this part of the schedule?.
        /// </summary>
        internal static string RemoveComponent {
            get {
                return ResourceManager.GetString("RemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} RTs, {1} favourites.
        /// </summary>
        internal static string RTAndFavCount {
            get {
                return ResourceManager.GetString("RTAndFavCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retweeted.
        /// </summary>
        internal static string RTDone {
            get {
                return ResourceManager.GetString("RTDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undid previous retweet.
        /// </summary>
        internal static string RTUndone {
            get {
                return ResourceManager.GetString("RTUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheduled times are entirely in the past..
        /// </summary>
        internal static string ScheduleIsInThePast {
            get {
                return ResourceManager.GetString("ScheduleIsInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT FOUND.  PLEASE ENTER CREDENTIALS..
        /// </summary>
        internal static string ScreenNameNotFound {
            get {
                return ResourceManager.GetString("ScreenNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds between tweets must be a positive number bigger of 1 or bigger..
        /// </summary>
        internal static string SecondsBetweenTweetsValidation {
            get {
                return ResourceManager.GetString("SecondsBetweenTweetsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signed in as {0}.
        /// </summary>
        internal static string SignedInAs {
            get {
                return ResourceManager.GetString("SignedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as {0}.
        /// </summary>
        internal static string SignedInAsMsgbox {
            get {
                return ResourceManager.GetString("SignedInAsMsgbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKZTweets.
        /// </summary>
        internal static string SKZTweets {
            get {
                return ResourceManager.GetString("SKZTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching account will stop all ongoing 
        ///processes and close all windows.
        ///It will also sign you out of Twitter and let 
        ///you sign in under another account.
        ///Do you wish to proceed?.
        /// </summary>
        internal static string SwitchAccountWarning {
            get {
                return ResourceManager.GetString("SwitchAccountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread complete. Posted {0} tweets..
        /// </summary>
        internal static string ThreadComplete {
            get {
                return ResourceManager.GetString("ThreadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No numbers.
        /// </summary>
        internal static string ThreadNumberingStyleNoNumbers {
            get {
                return ResourceManager.GetString("ThreadNumberingStyleNoNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string ThreadNumberingStyleX {
            get {
                return ResourceManager.GetString("ThreadNumberingStyleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X/Y.
        /// </summary>
        internal static string ThreadNumberingStyleXofY {
            get {
                return ResourceManager.GetString("ThreadNumberingStyleXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of tweet.
        /// </summary>
        internal static string ThreadNumberPositionEnd {
            get {
                return ResourceManager.GetString("ThreadNumberPositionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of tweet (after any intro).
        /// </summary>
        internal static string ThreadNumberPositionStart {
            get {
                return ResourceManager.GetString("ThreadNumberPositionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} tasks completed.
        /// </summary>
        internal static string ThreadProgress {
            get {
                return ResourceManager.GetString("ThreadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be specified in the format HH:MM..
        /// </summary>
        internal static string TimeNotValidEnd {
            get {
                return ResourceManager.GetString("TimeNotValidEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be specified in the format HH:MM..
        /// </summary>
        internal static string TimeNotValidStart {
            get {
                return ResourceManager.GetString("TimeNotValidStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timed process has been stopped due to an error..
        /// </summary>
        internal static string TimerStoppedDueToError {
            get {
                return ResourceManager.GetString("TimerStoppedDueToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet does not exist.
        /// </summary>
        internal static string TweetDoesNotExist {
            get {
                return ResourceManager.GetString("TweetDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweets deleted..
        /// </summary>
        internal static string TweetsDeleted {
            get {
                return ResourceManager.GetString("TweetsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet with id \&quot;{0}\&quot; does not exist.
        /// </summary>
        internal static string TweetWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("TweetWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While {0}, Twitter reported error number [{1}]. with the following message:
        ///{2}.
        /// </summary>
        internal static string TwitterError {
            get {
                return ResourceManager.GetString("TwitterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter reported error number {0}. The reason given was &quot;{1}&quot;.
        /// </summary>
        internal static string TwitterErrorGeneric {
            get {
                return ResourceManager.GetString("TwitterErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will retweet at {0}.
        /// </summary>
        internal static string WillRTAt {
            get {
                return ResourceManager.GetString("WillRTAt", resourceCulture);
            }
        }
    }
}
